/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jeeatwork.spring.spel.examples;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    private static final Logger logger = Logger.getLogger(App.class.getName());

    @Value("#{T(java.nio.file.Files).readString(T(java.nio.file.Path).of('${PASSWORD_FILE}'))}")
    private String password;

    public String getPassword() {
        return password;
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Bean
    public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
        return args -> logger.log(Level.INFO, getPassword());
    }
}
